# Generated by Django 5.1.5 on 2025-01-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limite_stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
